name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'     
        required: true
        default: 'review'
        type: choice
        options:
        - review
        - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        run: echo "BUILD"
  deployment:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Deployment
        run: echo "DEPLOYMENT"

