name: CI

on:
  create

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - if: ${{ github.event.ref_type == 'branch' }}
        run: |
          title="[${{ github.event.ref }}]$(git log -1 --format=%s)"
          body="$(git log -1 --format=%b)"
          gh pr create --title "${title}" --body "${body}" --assignee "${{ github.actor }}"
