name: CI

on:
  create

jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - if: ${{ github.event.ref_type == 'branch' }}
        run: |
          gh pr create --fill --assignee=${{ github.actor }}
