name: CI

on:
  pull_request:
    types:
    - closed

concurrency: "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sleep 2m
      - run: git rev-parse HEAD


