name: CI

on:
  create

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - if: ${{ github.event.ref_type == 'branch' }}
        run: |
          export
          echo "${{ github }}"
          gh pr create --title "[${{ github.event.ref }}]" --body "foo" --assignee "${{ github.actor }}"
