name: CI

on:
  pull_request:
    types:
    - synchronize
  push:

concurrency: "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ github.ref_name }}
      - run: export
