name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo github.event.pull_request.base.ref=${{ github.event.pull_request.base.ref }}
          echo github.event.pull_request.base.sha=${{ github.event.pull_request.base.sha }}
          git log origin/${{ github.event.pull_request.base.ref }} -1 --oneline
