name: CI

on:
  push:
    branches-ignore:
      - 'production'
    tags:
      - 'v[0-9].[0-9][0-9].[0-9][0-9]'

concurrency: "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: export
