name: PR Comment

on:
  issue_comment:
    types: [created]  

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Comment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo /repos/${{ github.event.repository }}/pulls/${{ github.event.issue.number }}
          gh api /repos/${{ github.event.repository }}/pulls/${{ github.event.issue.number }}
