name: PR Comment

on:
  issue_comment:
    types: [created]  

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Comment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'PULL_REQUEST<<EOF' >> $GITHUB_ENV
          gh api ${{ github.event.issue.pull_request.url }} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo ${{ env.PULL_REQUEST }}
          
          # gh issue comment ${{ github.event.issue.number }} --body="Hi from Github Actions" --repo=${{ github.repository }}
          
          # gh run list --branch={{ $env.BRANCH }} --repo=${{ github.repository }} --workflow="CI"
