name: PR Comment

on:
  issue_comment:
    types: [created]  

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Comment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=`gh api ${{ github.event.issue.pull_request.url }} | jq ".head.ref"`
          gh issue comment ${{ github.event.issue.number }} --body="Hi from Github Actions" --repo=${{ github.repository }}
          gh run list --branch=${BRANCH} --repo=${{ github.repository }} --workflow="CI"
