name: PR Comment

on:
  issue_comment:
    types: [created]  

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Comment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api ${{ github.event.issue.pull_request.url }}
          gh issue comment ${{ github.event.issue.url }} --body "Hi from Github Actions"
