name: PR Comment

on:
  issue_comment:
    types: [created]  

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Comment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
