on:
  push:
    branches:
    - main


jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: $PSVersionTable
        shell: pwsh
      - run: pwsh -Command $PSVersionTable
      - run: |-
          import subprocess
          subprocess.check_call("pwsh -Command $PSVersionTable")
        shell: python
