on:
  push:
    branches:
    - main


jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |-
          ln -s ~/.local/bin/powershell /usr/bin/pwsh
          python -c 'import subprocess; subprocess.check_call("powershell -Command Invoke-WebRequest -Uri https://google.de", shell=True)'
